language: node_js
sudo: true
node_js:
  - "11"

env:
  - ZOLA_VERSION=0.5.1 DEPLOY_URL=https://cogoldrust.com

before_script:
  - bash scripts/setup.sh

jobs:
  include:
    - stage: test
      script:
        - bash scripts/build.sh
        - npm run deploy
    - stage: deploy
      script:
        - bash scripts/build.sh
        - npm run deploy -- --prod

stages:
  - name: test
    if: NOT branch = master
  - name: deploy
    if: branch = master
