[[talks]]
name = "Katharina Fey"
title = "Opening Keynote"
flag = "keynote"
localtime = "9:30AM"

[[talks]]
flag = "break"
localtime = "10:30AM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "11:00AM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "11:30AM"

[[talks]]
name = "Free Time"
title = "Lunch"
flag = "freetime"
localtime = "12:00PM-2:00PM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "2:00PM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "2:30PM"

[[talks]]
flag = "break"
localtime = "3:00PM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "3:30PM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "4:00PM"

[[talks]]
name = ""
title = ""
flag = "talk"
localtime = "4:30PM"

[[talks]]
name = "Colorado Gold Rust"
title = "Wrap-up"
flag = "announcement"
localtime = "5:00PM"
