[[talks]]
name = "Katharina Fey"
title = "Opening Keynote"
flag = "keynote"
localtime = "9:30AM"

[[talks]]
flag = "break"
localtime = "10:15AM"

[[talks]]
name = "data-pup"
title = "Option and Result: Cooking a Better Cupcake"
flag = "talk"
localtime = "10:30AM"

[[talks]]
name = "Ilya Baryshnikov"
title = "Practical tips about using DOM and JS APIs from Rust"
flag = "talk"
localtime = "11:00AM"

[[talks]]
name = "Free Time"
title = "Lunch"
flag = "freetime"
localtime = "11:30AM-1:30PM"

[[talks]]
name = "Cassie Jones"
title = "Artisanal Rendering: Make Your Own Computer Art!"
flag = "talk"
localtime = "1:30PM"

[[talks]]
name = "Igor Matuszewski"
title = "Are we actually IDE yet? - A look on current Rust IDE story"
flag = "talk"
localtime = "2:00PM"

[[talks]]
flag = "break"
localtime = "2:30PM"

[[talks]]
name = "Omar S. Navarro Leija"
title = "Futures From the Ground Up (For Beginners, by Beginners)"
flag = "talk"
localtime = "3:00PM"

[[talks]]
name = "Alan Somers"
title = "BFFFS: a novel SMR-native file system written in Rust"
flag = "talk"
localtime = "3:30PM"

[[talks]]
flag = "break"
localtime = "4:00PM"

[[talks]]
name = "Zack Pierce"
title = "A Tour of Empirical Verification in Rust"
flag = "talk"
localtime = "4:30PM"

[[talks]]
name = "Jane Lusby"
title = "Rustaceans! We Can Help!"
flag = "talk"
localtime = "5:00PM"

[[talks]]
name = "Colorado Gold Rust"
title = "Wrap-up"
flag = "announcement"
localtime = "5:30PM"
